// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// This file is the central source of truth for the Prisma CLI in Prisma 7.
// It decouples the data structure (schema.prisma) from connectivity (DATABASE_URL),
// ensuring the CLI always knows where to find the schema, migrations, and how to connect.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
